spring.application.name=client

server.port=8001
server.address=0.0.0.0
propertiesspring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
